name: Python CI

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install
        run: |
          poetry install
          poetry run python -m playwright install-deps chromium
          poetry run python -m playwright install chromium

      - name: Run tests
        run: poetry run pytest -v --cov=playwright_har_tracer --cov-report=term-missing

      - name: Coveralls
        env:
          COVERALLS_PARALLEL: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: poetry run coveralls
